kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-manager-app-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-resource-control
subjects:
  - kind: ServiceAccount
    name: resource-manager
