kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-resource-control
rules:
  - apiGroups: ["", "apps"]
    resources:
      - deployments
      - pods
      - services
      - services/proxy
    verbs: ["create", "delete", "get", "list", "watch"]
